version: '2'
services:
  app:
    build: .
    command: node src/index.js
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app/
      - /home/app/node_modules
